# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sQfS6R9agCkp0i3-ukKMJBLDu_Jx9bjj
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd

df = pd.read_json('contacts.json')

df

emailDict = {}

for i in range(len(df)):
  if df.iloc[i, 1] != '':
    _email = df.iloc[i, 1]
    if _email in emailDict:
      emailDict[_email].append(df.iloc[i, 0])
    else:
      emailDict[_email] = list()
      emailDict[_email].append(df.iloc[i, 0])

phoneDict = {}

for i in range(len(df)):
  if df.iloc[i, 2] != '':
    _phone = df.iloc[i, 2]
    if _phone in phoneDict:
      phoneDict[_phone].append(df.iloc[i, 0])
    else:
      phoneDict[_phone] = list()
      phoneDict[_phone].append(df.iloc[i, 0])

orderDict = {}

for i in range(len(df)):
  if df.iloc[i, 4] != '':
    _order = df.iloc[i, 4]
    if _order in orderDict:
      orderDict[_order].append(df.iloc[i, 0])
    else:
      orderDict[_order] = list()
      orderDict[_order].append(df.iloc[i, 0])

class DisjSet: 
    def __init__(self, n): 
        self.rank = [1] * n 
        self.parent = [i for i in range(n)] 

    def find(self, x): 
        if (self.parent[x] != x): 
            self.parent[x] = self.find(self.parent[x])
        return self.parent[x] 

    def Union(self, x, y): 
        xset = self.find(x) 
        yset = self.find(y) 
        if xset == yset: 
            return
        if self.rank[xset] < self.rank[yset]: 
            self.parent[xset] = yset 
        elif self.rank[xset] > self.rank[yset]: 
            self.parent[yset] = xset 
        else: 
            self.parent[yset] = xset 
            self.rank[xset] = self.rank[xset] + 1

obj = DisjSet(500000)

for _email in emailDict:
  _prev = emailDict[_email][0]
  for i in range(len(emailDict[_email]) - 1):
    obj.Union(_prev, emailDict[_email][i + 1])
    prev = emailDict[_email][i + 1]

for _phone in phoneDict:
  _prev = phoneDict[_phone][0]
  for i in range(len(phoneDict[_phone]) - 1):
    obj.Union(_prev, phoneDict[_phone][i + 1])
    prev = phoneDict[_phone][i + 1]

for _order in orderDict:
  _prev = orderDict[_order][0]
  for i in range(len(orderDict[_order]) - 1):
    obj.Union(_prev, orderDict[_order][i + 1])
    prev = orderDict[_order][i + 1]

out = ['' for x in range(500000)]
cnt = [0 for x in range(500000)]

for i in range(500000):
  x = obj.find(i)
  cnt[x] += df.iloc[i, 3]
  if out[x] == '':
    out[x] = str(i)
  else:
    out[x] += '-'
    out[x] += str(i)

for i in range(500000):
  out[i] += ', '
  out[i] += str(cnt[i])

outt = ['' for x in range(500000)]

for i in range(500000):
  outt[i] = out[obj.find(i)]

output = pd.DataFrame(outt, columns = ['ticket_trace/contact'])

from google.colab import drive
drive.mount('/drive')
output.to_csv('submission3.csv', index=True, index_label = 'ticket_id', header=True)